#
WRITE YOUR MYSQL QUERY STATEMENT BELOW

# HANDLE THE CASE WHEN WE HAVE USERS WHO DO NOT TRAVEL ANY MILES

SELECT NAME,
       IFNULL(SUM(R.DISTANCE),
              0) AS TRAVELLED_DISTANCE
FROM USERS U
         LEFT JOIN RIDES R
                   ON U.ID = R.USER_ID
GROUP BY R.USER_ID
ORDER BY TRAVELLED_DISTANCE DESC,
         U.NAME;