#
WRITE YOUR MYSQL QUERY STATEMENT BELOW

SELECT P.FIRSTNAME,
       P.LASTNAME,
       A.STATE,
       A.CITY
FROM PERSON P
         LEFT JOIN ADDRESS A
                   ON P.PERSONID = A.PERSONID;