-- # WRITE YOUR MYSQL QUERY STATEMENT BELOW

SELECT USER_ID,
       MAX(TIME_STAMP) AS LAST_STAMP
FROM LOGINS
WHERE TIME_STAMP BETWEEN '2020-01-01 00:00:00'
          AND '2020-12-31 23:59:59'
GROUP BY USER_ID;

-- The other way
-- # Write your MySQL query statement below
SELECT USER_ID,
       MAX(TIME_STAMP) AS LAST_STAMP
FROM LOGINS
WHERE YEAR(TIME_STAMP) = 2020
GROUP BY USER_ID;