-- # PLEASE WRITE A DELETE STATEMENT AND DO NOT WRITE A SELECT STATEMENT.

-- # WRITE YOUR MYSQL QUERY STATEMENT BELOW

-- # DO A SELF JOIN HERE, AND KEEP THE SMALLEST ID THAT HAS DUPLICTE ROWS

DELETE P1.* FROM PERSON P1,
    PERSON P2
WHERE
    P1.EMAIL = P2.EMAIL
  AND P1.ID
    > P2.ID;